---
all:
  children:
    webservers:
      hosts:
        webserver01.staging:
          ansible_host: 192.168.1.10
    databases:
      hosts:
        db01.staging:
          ansible_host: 192.168.1.20
